version: "2.1"
services:



 etherpadlite:
    build: .
    container_name: EtherPadLite
    restart: unless-stopped
    volumes:
      - ./etherpad-lite/var:/opt/etherpad-lite/var
      - ./etherpad-lite/node_modules:/opt/etherpad-lite/node_modules
    ports:
      - "9001:9001"
    environment:
     - ETHERPAD_ADMIN_PASSWORD=78051ac7
    networks:
     - dbnet





networks:
  dbnet:
    external: true
    name: dbnet
